name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:  
  build_runner: ^2.3.3
  db:
    git:
      url: https://github.com/loctt-executionlab/shared_db.git
      ref: main
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
dependencies_override:
  analyzer: ^5.2.0

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
